import type { AppUser, Booking, Conversation, Review, Ride, Vehicle } from "./types"

export const currentUserId = "alex"

export const users: AppUser[] = [
  {
    id: "alex",
    name: "Alex Morgan",
    firstName: "Alex",
    phone: "(917) 555-0148",
    bio: "Splits time between Brooklyn and New England. Punctual, light packer, happy to share playlists.",
    rating: 4.9,
    reviews: 27,
    verified: true,
    symbol: "AM",
  },
  {
    id: "mae",
    name: "Mae Carter",
    firstName: "Mae",
    phone: "(401) 555-0192",
    bio: "Newport local, usually driving between SoHo and Aquidneck Island for work.",
    rating: 4.98,
    reviews: 64,
    verified: true,
    symbol: "MC",
  },
  {
    id: "sam",
    name: "Sam Patel",
    firstName: "Sam",
    phone: "(617) 555-0108",
    bio: "Product designer in Boston. Quiet car, clean trunk, coffee stops negotiable.",
    rating: 4.86,
    reviews: 41,
    verified: true,
    symbol: "SP",
  },
  {
    id: "nina",
    name: "Nina Brooks",
    firstName: "Nina",
    phone: "(203) 555-0181",
    bio: "Weekend traveler and early train alternative seeker.",
    rating: 4.81,
    reviews: 15,
    verified: false,
    symbol: "NB",
  },
  {
    id: "jordan",
    name: "Jordan Lee",
    firstName: "Jordan",
    phone: "(215) 555-0134",
    bio: "Usually between Center City and Navy Yard meetings. Reliable pickup windows.",
    rating: 4.92,
    reviews: 38,
    verified: true,
    symbol: "JL",
  },
  {
    id: "priya",
    name: "Priya Shah",
    firstName: "Priya",
    phone: "(202) 555-0173",
    bio: "DC-based consultant with regular Northeast Corridor drives.",
    rating: 4.88,
    reviews: 52,
    verified: true,
    symbol: "PS",
  },
]

export const vehicles: Vehicle[] = [
  { id: "mae-car", ownerId: "mae", make: "Volvo", model: "XC60", color: "Sage", year: 2023, plateState: "RI" },
  { id: "sam-car", ownerId: "sam", make: "Tesla", model: "Model 3", color: "White", year: 2022, plateState: "MA" },
  { id: "alex-car", ownerId: "alex", make: "Toyota", model: "RAV4", color: "Black", year: 2022, plateState: "NY" },
  { id: "jordan-car", ownerId: "jordan", make: "Subaru", model: "Outback", color: "Blue", year: 2021, plateState: "PA" },
  { id: "priya-car", ownerId: "priya", make: "Honda", model: "CR-V", color: "Gray", year: 2023, plateState: "DC" },
]

export const rides: Ride[] = [
  {
    id: "nyc-newport",
    driverId: "mae",
    vehicleId: "mae-car",
    origin: "New York, NY",
    destination: "Newport, RI",
    departureTime: "Tomorrow, 8:15 AM",
    pickupNotes: "SoHo pickup near Canal St. Easy subway access.",
    dropoffNotes: "Newport Gateway Center, flexible downtown drop.",
    seatsAvailable: 3,
    totalSeats: 4,
    price: 48,
    luggage: "Carry-on",
    preferences: ["No smoking", "Quiet ride", "Phone charger"],
    manualApproval: false,
    status: "active",
  },
  {
    id: "nyc-providence",
    driverId: "sam",
    vehicleId: "sam-car",
    origin: "New York, NY",
    destination: "Providence, RI",
    departureTime: "Tomorrow, 4:30 PM",
    pickupNotes: "Meet outside Moynihan Train Hall on 31st St.",
    dropoffNotes: "Dropoff by Providence Station.",
    seatsAvailable: 2,
    totalSeats: 3,
    price: 39,
    luggage: "Backpack",
    preferences: ["No smoking", "Music okay"],
    manualApproval: true,
    status: "active",
  },
  {
    id: "boston-nyc",
    driverId: "sam",
    vehicleId: "sam-car",
    origin: "Boston, MA",
    destination: "New York, NY",
    departureTime: "Sunday, 7:45 AM",
    pickupNotes: "Back Bay curbside pickup.",
    dropoffNotes: "Upper West Side or Midtown East.",
    seatsAvailable: 1,
    totalSeats: 3,
    price: 52,
    luggage: "Carry-on",
    preferences: ["Quiet ride", "Phone charger"],
    manualApproval: false,
    status: "active",
  },
  {
    id: "new-haven-nyc",
    driverId: "alex",
    vehicleId: "alex-car",
    origin: "New Haven, CT",
    destination: "New York, NY",
    departureTime: "Sunday, 6:10 PM",
    pickupNotes: "Union Station pickup by the taxi stand.",
    dropoffNotes: "Grand Central or Williamsburg by request.",
    seatsAvailable: 2,
    totalSeats: 3,
    price: 24,
    luggage: "Backpack",
    preferences: ["No smoking", "Music okay", "Phone charger"],
    manualApproval: true,
    status: "active",
  },
  {
    id: "philly-dc",
    driverId: "jordan",
    vehicleId: "jordan-car",
    origin: "Philadelphia, PA",
    destination: "Washington, DC",
    departureTime: "Friday, 2:20 PM",
    pickupNotes: "30th Street Station west entrance.",
    dropoffNotes: "Union Station or Dupont Circle by request.",
    seatsAvailable: 3,
    totalSeats: 4,
    price: 31,
    luggage: "Carry-on",
    preferences: ["No smoking", "Music okay", "Pets allowed"],
    manualApproval: false,
    status: "active",
  },
  {
    id: "dc-nyc",
    driverId: "priya",
    vehicleId: "priya-car",
    origin: "Washington, DC",
    destination: "New York, NY",
    departureTime: "Saturday, 9:00 AM",
    pickupNotes: "Meet near Union Station rideshare zone.",
    dropoffNotes: "Moynihan Train Hall or Downtown Brooklyn.",
    seatsAvailable: 2,
    totalSeats: 3,
    price: 56,
    luggage: "Large suitcase",
    preferences: ["No smoking", "Quiet ride", "Phone charger"],
    manualApproval: true,
    status: "active",
  },
]

export const bookings: Booking[] = [
  {
    id: "seed-booking",
    rideId: "new-haven-nyc",
    riderId: "nina",
    seats: 1,
    status: "pending",
    payment: {
      id: "payment-seed",
      amount: 24,
      status: "authorized",
      note: "Stripe authorization held until driver approval.",
    },
    createdAt: "Today",
  },
]

export const conversations: Conversation[] = [
  {
    id: "conversation-seed",
    rideId: "new-haven-nyc",
    bookingId: "seed-booking",
    participantIds: ["alex", "nina"],
    messages: [
      { id: "msg-1", senderId: "nina", body: "Hi Alex, I can meet 10 minutes early.", sentAt: "12:35 PM" },
      { id: "msg-2", senderId: "alex", body: "Perfect. I will be in the black RAV4.", sentAt: "12:40 PM" },
    ],
  },
]

export const reviews: Review[] = [
  {
    id: "review-1",
    authorId: "alex",
    subjectId: "mae",
    rating: 5,
    body: "Mae was calm, prompt, and the car was spotless.",
  },
  {
    id: "review-2",
    authorId: "mae",
    subjectId: "alex",
    rating: 5,
    body: "Alex was easy to coordinate with and ready at pickup.",
  },
]

export const popularRoutes = [
  ["New York, NY", "Newport, RI"],
  ["New York, NY", "Providence, RI"],
  ["Boston, MA", "New York, NY"],
  ["Philadelphia, PA", "Washington, DC"],
  ["Washington, DC", "New York, NY"],
  ["New Haven, CT", "New York, NY"],
]

export const cities = [
  "New York, NY",
  "Boston, MA",
  "Providence, RI",
  "Newport, RI",
  "New Haven, CT",
  "Stamford, CT",
  "Hoboken, NJ",
  "Philadelphia, PA",
  "Baltimore, MD",
  "Washington, DC",
]
